version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: Trustlink_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sp00dy$4523
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  trustlink:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Trustlink_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sp00dy$4523

volumes:
  postgres_data: