spring.application.name=Trustlink

#Database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/Trustlink_db
spring.datasource.username=postgres
spring.datasource.password=Sp00dy$4523
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#App configurations
server.port=8080
trustlink.rate.limit.max-requests=20
trustlink.rate.limit.window-seconds=60
trustlink.payload.max-size-bytes=10240
trustlink.auto-blacklist.block-threshold=3
trustlink.probing.max-not-found=5
trustlink.auto-blacklist.window-minutes=10
trustlink.auto-blacklist.expiry-hours=24
